version: '3.7'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    # command: /home/app/runner.sh
    command: /home/app/init.sh
    environment:
      PYTHONUNBUFFERED: 1
      ADDRESS_PORT: "localstack:4566"
    depends_on:
      - localstack

